### ISSUE TITLE
URI::InvalidURIError: bad URI(is not URI?): "http://api.example.co"

### ISSUE THREAD

**Issue by prcongithub** [jruby/docker-jruby#51]
Dockerfile

```
FROM jruby:9.1.15.0

RUN apt-get update -qq && \
    apt-get install -y nano build-essential libpq-dev git imagemagick gcc g++ && \
    gem install bundler
    
RUN mkdir /project

COPY Gemfile Gemfile.lock /project/

WORKDIR /project

RUN bundle install

COPY . /project

```

Stacktrace

```
! Unable to load application: URI::InvalidURIError: bad URI(is not URI?): "http://authapilocal.es-q.co"
sq_api_1  | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
sq_api_1  | URI::InvalidURIError: bad URI(is not URI?): "http://authapilocal.es-q.co"
sq_api_1  |   /project/config/initializers/vger.rb:97:in `split'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/uri/rfc3986_parser.rb:73:in `parse'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/uri/common.rb:237:in `parse'
sq_api_1  |   /project/config/initializers/vger.rb:107:in `<main>'
sq_api_1  |   org/jruby/RubyKernel.java:1029:in `load'
sq_api_1  |   /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:1:in `block in (root)'
sq_api_1  |   /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
sq_api_1  |   /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
sq_api_1  |   /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/engine.rb:657:in `load_config_initializer'
sq_api_1  |   /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/engine.rb:656:in `block in load_config_initializer'
sq_api_1  |   org/jruby/RubyArray.java:1792:in `each'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/engine.rb:614:in `block in Engine'
sq_api_1  |   org/jruby/RubyBasicObject.java:2681:in `instance_exec'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:228:in `block in tsort_each'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:350:in `block in each_strongly_connected_component'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:422:in `block in each_strongly_connected_component_from'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:431:in `each_strongly_connected_component_from'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:421:in `block in each_strongly_connected_component_from'
sq_api_1  |   org/jruby/RubyArray.java:1792:in `each'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:50:in `tsort_each_child'
sq_api_1  |   org/jruby/RubyMethod.java:120:in `call'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:415:in `each_strongly_connected_component_from'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:349:in `block in each_strongly_connected_component'
sq_api_1  |   org/jruby/RubyArray.java:1792:in `each'
sq_api_1  |   org/jruby/RubyMethod.java:132:in `call'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/engine.rb:613:in `Engine'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:347:in `each_strongly_connected_component'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:226:in `tsort_each'
sq_api_1  |   /opt/jruby/lib/ruby/stdlib/tsort.rb:205:in `tsort_each'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
sq_api_1  |   /usr/local/bundle/gems/railties-5.2.0/lib/rails/application.rb:361:in `<main>'
sq_api_1  |   org/jruby/RubyKernel.java:987:in `require'
sq_api_1  |   org/jruby/RubyKernel.java:1015:in `require_relative'
sq_api_1  |   /project/config/environment.rb:5:in `block in <main>'
sq_api_1  |   org/jruby/RubyBasicObject.java:2609:in `instance_eval'
sq_api_1  |   config.ru:1:in `(root)'
sq_api_1  |   config.ru:3:in `new_from_string'
sq_api_1  |   org/jruby/RubyKernel.java:1061:in `eval'
sq_api_1  |   /usr/local/bundle/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
sq_api_1  |   config.ru:1:in `new_from_string'
sq_api_1  |   /usr/local/bundle/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
sq_api_1  |   /usr/local/bundle/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/lib/puma/configuration.rb:318:in `load_rackup'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/lib/puma/configuration.rb:243:in `app'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/lib/puma/runner.rb:138:in `load_and_bind'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/lib/puma/single.rb:87:in `run'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/lib/puma/launcher.rb:183:in `<main>'
sq_api_1  |   org/jruby/RubyKernel.java:1022:in `load'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/lib/puma/cli.rb:77:in `<main>'
sq_api_1  |   org/jruby/RubyKernel.java:1022:in `load'
sq_api_1  |   /usr/local/bundle/gems/puma-3.11.2-java/bin/puma:10:in `<main>'
sq_api_1  |   /usr/local/bundle/bin/puma:1:in `(root)'
sq_api_1  |   /usr/local/bundle/bin/puma:29:in `<main>'
```

**Comment by cpuguy83** [comment]
This seems like an application issue?
